src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\Common\Collections\ArrayCollections;
use Doctrine\Common\Collections\Collections;

/**
 * @ORM\Entity(repositoryClass=CommentsRepository::class)
 */
class Comments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="date")
     * @Groups("comments:read")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Publication::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $publications;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $user_id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPublications(): ?Publication
    {
        return $this->publications;
    }

    public function setPublications(?Publication $publications): self
    {
        $this->publications = $publications;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(?int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/PublicationType.php
<?php

namespace App\Form;

use App\Entity\Publication;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Validator\Constraints\File;

class PublicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('titre')
        ->add('text', CKEditorType::class)
        ->add('userid', HiddenType::class)
        ->add('image', FileType::class,[
            'label' => 'image',
            'mapped' => false,
            'required' => false,
            'constraints' => [
                new File([
                    'maxSize' => '2Mi',
                    'mimeTypesMessage' => 'Please upload a valid image file',
                ])
            ],
        ])
        ->add('useremail', HiddenType::class)
      /* ->add('date',DateType::class, array(
            'widget' => 'single_text',            
            'format' => 'yyyy-MM-dd',
            'data' => new \DateTime(),
            'attr' => [
                'disabled' => true,
                'hidden' => true

            ]
            
        ))*/
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Publication::class,
        ]);
    }
}

src/Controller/PublicationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\PublicationType;
use App\Entity\Publication;
use App\Repository\PublicationRepository;
use App\Repository\PublicationLikeRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Sension\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use App\Entity\Comments;
use App\Form\CommentsType;
use App\Repository\CommentsRepository;
use App\Entity\PublicationLike;
use App\Repository\UserRepository;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\PaginatorInterface;

class PublicationController extends AbstractController
{
    /**
     * @Route("/publication", name="publication")
     */
    public function index(PublicationRepository $repository, PaginatorInterface $paginator, Request $request)
    {
        $publication=$repository->findAll();

        $e = $paginator->paginate(
            $publication,
            $request->query->getInt('page', 1),
            3
        );
        return $this->render('publication/index.html.twig',['publication'=>$e]);
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\\HttpFoundation\Response
     * @Route("publication/Add", name="ajouter_publication")
     */
    function Add(Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository){
        $publication = new Publication();
        $user=$this->getUser();       
        $publication->setUser($user);
        $form=$this->createForm(PublicationType::class,$publication);
        $form->add('Ajouter',SubmitType::class,
    ['attr'=>['formnovalidate'=> 'formnovalidate']]); 
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid()){

              /** @var UploadedFile $imageFile */
              $imageFile = $form->get('image')->getData();

              if ($imageFile) {
                  $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                  $newFilename = $originalFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();
                  try {
                      $imageFile->move(
                          $this->getParameter('images_directory'),
                          $newFilename
                      );
                  } catch (FileException $e) {
                      // ... handle exception if something happens during file upload
                  }
                  $publication->setImage($newFilename);
                  $date = new \DateTime('now');
            $publication->setDate($date);
                  $entityManager->persist($publication);
                  $entityManager->flush();
                  $this->addFlash('message', 'la publication a bien ete ajouter ');
                  return $this->redirectToRoute('publication');
              } else {
                $date = new \DateTime('now');
                $publication->setDate($date);
                  $entityManager->persist($publication);
                  $entityManager->flush();
                  $this->addFlash('message', 'la publication a bien ete ajouter ');
                  return $this->redirectToRoute('publication');
              }

        }
        return $this->render('publication/Add.html.twig',[
            'f'=>$form->createView()
        ]);
            }

            
/**
     * @Route("publication/edit/{id}", name="publication_edit")
     */
    public function edit(Request $request, Publication $publication, EntityManagerInterface $entityManager, $id, PublicationRepository $repository, UserRepository $userRepository): Response
    {
        $publication=$repository->find($id);
        $user=$this->getUser();       
        $publication->setUser($user);
        $form = $this->createForm(PublicationType::class, $publication);
        $form->add('Modifier',SubmitType::class,
    ['attr'=>['formnovalidate'=> 'formnovalidate']]); 
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
              /** @var UploadedFile $imageFile */
              $imageFile = $form->get('image')->getData();

              if ($imageFile) {
                  $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                  $newFilename = $originalFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();
                  try {
                      $imageFile->move(
                          $this->getParameter('images_directory'),
                          $newFilename
                      );
                  } catch (FileException $e) {
                      // ... handle exception if something happens during file upload
                  }
                  $publication->setImage($newFilename);
                  $date = new \DateTime('now');
                $publication->setDate($date);
                  $entityManager->persist($publication);
                  $entityManager->flush();
                 
                  return $this->redirectToRoute('publication');
              } else {
                $date = new \DateTime('now');
                $publication->setDate($date);
                  $entityManager->persist($publication);
                  $entityManager->flush();
               
                  return $this->redirectToRoute('publication');
              }
        }

        return $this->render('publication/edit.html.twig', [
            'publication' => $publication,
            'f' => $form->createView(),
        ]);
    }


    /**
     * @param PublicationRepository $repository
     * @return \Symfony\Component\\HttpFoundation\Response
     * @Route("/AffichePublication", name="AffichePublication")
     */
    public function Affiche(PublicationRepository $repository){
        
        $publication=$repository->findAll();
        return $this->render('publication/Affiche.html.twig',['publication'=>$publication]);
    }

        /**
         * @param $id
         * @param $repository
         * @return \Symfony\Component\\HttpFoundation\RedirectResponse
     * @Route("publication/Delete/{id}", name="delete_pub")
     */
    public function Delete($id, PublicationRepository $repository){
        $publication=$repository->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($publication);
        $em->flush();
        return $this->redirectToRoute('AffichePublication');
            }


               /**
     * @param PublicationRepository $repository
     * @param CommentsRepository $commentrepository
     * @return \Symfony\Component\\HttpFoundation\Response
     * @Route("publication/details/{id}", name="details_publication")
     */
    public function Details(PublicationRepository $repository, $id, Request $request, CommentsRepository $commentrepository, UserRepository $userRepository)
    {
        
       // $publication = $repository->findOneBy(['id' => $id]);
        $publication= $this->getDoctrine()->getManager()
        ->getRepository(Publication::class)
        ->find($request->get("id"));

        if(!$publication){
            throw new NotFoundHttpException('Pas de publication trouvée');
        }


        // Partie commentaires
        // On crée le commentaire "vierge"
        $comment = new Comments();


        $user=$this->getUser();       
        $comment->setUser($user);


        // On génère le formulaire
        $commentForm = $this->createForm(CommentsType::class, $comment);
        $commentForm->add('Ajouter',SubmitType::class); 
        $commentForm->handleRequest($request);
        if($commentForm->isSubmitted() && $commentForm->isValid()){
            $date = new \DateTime('now');          
            $comment->setCreatedAt($date);
            $comment->setPublications($publication);
            $comment->setUserId(24);

            $em = $this->getDoctrine()->getManager();
            $em->persist($comment);
            $em->flush();

            return $this->redirectToRoute('details_publication', ['id' => $publication->getId()]);
        }

        //parti modification du commentaire


        //$commentaire=$commentrepository->find($idComment);
        $commentaire=$this->getDoctrine()->getManager()->getRepository(Comments::class)->find($request->get("id"));
        $form=$this->createForm(CommentsType::class,$commentaire);
        $form->add('Update',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('details_publication', ['id' => $publication->getId()]);
        }
        
        // Fin partie modifier commentaire






  //parti Suppression du commentaire

        //$comments=$this->getDoctrine()->getManager()->getRepository(Comments::class)->find($request->get("id"));
        //$comments=$this->getDoctrine()->getManager()->getRepository(Comments::class)->find($request->get("id"));
        /*$comments=$commentrepository->find($idcomment);
        $deleteForm=$this->createForm(CommentsType::class,$comments);
        $deleteForm->add('supprimer',SubmitType::class);
        $deleteForm->handleRequest($request);
        if($deleteForm->isSubmitted() && $deleteForm->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->remove($comments);
            $em->flush();
            return $this->redirectToRoute('details_publication', ['id' => $publication->getId()]);
        }*/
        

templates/publication/Add.html.twig
{% extends 'base2.html.twig' %}
{% block title %}
<title>OutWithUs- Ajouter une publication</title>
{% endblock %}
{% block body %}


<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Ajouter Publication</h2>
      <ol>
        <li><a href="index.html">Home</a></li>
      </ol>
    </div>

  </div>
</section>
<!-- End Breadcrumbs -->

<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">

    <div class="row">

      <div class="col-lg-8 entries">

  
   
    <div class="row mt">
      <div class="col-lg-12">
        <div class="form-panel">
          <div class="form">
            {{ form_start(f,{'attr':{'class':'cmxform form-horizontal style-form', 'novalidate':'novalidate'}}) }}
              <div class="form-group ">
                <label class="control-label col-lg-2">Titre</label>
                <div class="col-lg-10">
              
                  {{form_widget(f.titre,{'attr':{'class':'form-control', 'placeholder': 'Le titre du publication'}})}}
                  {{form_errors(f.titre,{'attr':{'class':'text-danger'}}) }}
                </div>
              </div>
              <div class="form-group ">
                <label class="control-label col-lg-2">Text</label>
                <div class="col-lg-10">
              
                  {{form_widget(f.text,{'attr':{'class':'form-control'}})}}
                  {{form_errors(f.text,{'attr':{'class':'text-danger'}}) }}
                </div>
              </div>
              <div class="form-group ">
                <label class="control-label col-lg-3">Ajouter une image</label>
                <div class="col-lg-10">
              
                  {{form_widget(f.image,{'attr':{'class':'form-control'}})}}
                 
                </div>
              </div>
           
              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                 
                  {{form_widget(f.Ajouter,{'attr':{'class':'btn btn-danger'}})}}
                </div>
              </div>
                      {{ form_end(f) }}
          </div>
       
          <br>         
        </div>     
      </div>
      </div> 
              
    </div>     
  </div>
  </div>   
</section>

 


{% endblock %}

templates/publication/Affiche.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<br /><br /><br /><br />


       <section id="main-content">
      <section class="wrapper">
        <h3><i class="fa fa-angle-right"></i> Liste des Publications</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
        
        
            <div class="adv-table">
              <table cellpadding="0" cellspacing="0" border="0" class="table table-hover" id="hidden-table-info">
                <thead>
                  <tr>
                    <th>Actions</th>
                    <th>Créateur</th>
                    <th>Titre</th>
                    <th>Text</th>
                    <th>Image</th>
                    <th>Date</th>
                   
                   
                    
                  </tr>
                </thead>
                <tbody>
         
          <tr {% for p in publication %}>

            <td>
              <a href="{{ path('publication_edit',{'id':p.id}) }}">Modifier</a>
              <a href="{{ path('delete_pub',{'id':p.id}) }}">Supprimer</a>
             
            </td>
            <td>{{ p.user.nom}}</td>
            <td>{{ p.titre }}</td>
               <td>{{ p.text|striptags }}</td>
               {% if p.image|length > 0 %}
               <td><img src="{{ asset('uploads/'~ p.image )|imagine_filter('square') }}" width="100" height="150"></td>
           {% else %}
               <td><img src="{{ asset('uploads/'~ "Not found.jpg" ) }}" width="100" height="150"></td>
           {% endif %}
           <td>{{ p.date ? p.Date|date('Y-m-d') : '' }}</td>
            
            
           



        </tr {% endfor %}>
                </tbody>
              </table>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>

{% endblock %}

templates/publication/AfficheComments.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<br /><br /><br /><br />


       <section id="main-content">
      <section class="wrapper">
        <h3><i class="fa fa-angle-right"></i> Liste des Commentaires</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
        
        
            <div class="adv-table">
              <table cellpadding="0" cellspacing="0" border="0" class="table table-hover" id="hidden-table-info">
                <thead>
                  <tr>
                    <th>Actions</th>
                    <th>Utilisateur</th>
                    <th>Publication</th>
                    <th>Commentaire</th>
                    <th>Date</th>
                    
                   
                    
                  </tr>
                </thead>
                <tbody>
         
          <tr {% for c in commentaires %}>

            <td>
                <a href="{{ path('update_comment',{'id':c.id}) }}">Modifier</a>
                <a href="{{ path('supprimer_commentaire',{'id':c.id}) }}">Supprimer</a>
               
              </td>
            <td>{{ c.user.nom }}</td>
               <td>{{ c.publications.titre }}</td>
               <td>{{ c.content }}</td>
           <td>{{ c.createdAt ? c.createdAt|date('Y-m-d') : '' }}</td>
            
            
           



        </tr {% endfor %}>
                </tbody>
              </table>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>

{% endblock %}

templates/publication/AffichePubUser.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<br /><br /><br /><br />


       <section id="main-content">
      <section class="wrapper">
        <h3><i class="fa fa-angle-right"></i> Liste de vos Publications</h3>
        <div class="row mb">
          <!-- page start-->
          <div class="content-panel">
        
        
            <div class="adv-table">
              <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
                <thead>
                  <tr>
                   
                    <th>Titre</th>
                    <th>Text</th>
                    <th>Image</th>
                    <th>Date</th>
                    <th>Actions</th>
                   
                    
                  </tr>
                </thead>
                <tbody>
         
          <tr {% for p in publication %}>

           
            <td>{{ p.titre }}</td>
               <td>{{ p.text|striptags }}</td>
               {% if p.image|length > 0 %}
               <td><img src="{{ asset('uploads/'~ p.image )|imagine_filter('square') }}" width="250" height="150"></td>
           {% else %}
               <td><img src="{{ asset('uploads/'~ "Not found.jpg" ) }}" width="250" height="150"></td>
           {% endif %}
           <td>{{ p.date ? p.Date|date('Y-m-d') : '' }}</td>
            <td>
              <a href="{{ path('publication_edit',{'id':p.id}) }}">Modifier</a>
              <a href="{{ path('delete_pub',{'id':p.id}) }}">Supprimer</a>
             
            </td>
            
           



        </tr {% endfor %}>
                </tbody>
              </table>
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>

{% endblock %}

templates/publication/details.html.twig
{% extends 'base2.html.twig' %}

{% block title %}
<title>OutWithUs- Publication single</title>
{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

<script src="{{ asset('js/scripts.js')}}"></script>


 <!-- ======= Breadcrumbs ======= -->
 <section id="breadcrumbs" class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Publication par {{ publication.user.nom }} {{ publication.user.prenom }}</h2>
     
    </div>

  </div>
</section><!-- End Breadcrumbs -->




<!-- ======= Blog Single Section ======= -->
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">

    <div class="row">

      <div class="col-lg-8 entries">

        <article class="entry entry-single">

          <div class="entry-img">
            {% if publication.image|length > 0 %}
                <img src="{{ asset('uploads/'~ publication.image ) }}" alt="" class="img-fluid">
                {% else %}
                <img src="{{ asset('uploads/'~ "Not Found.jpg" ) }}" alt="" class="img-fluid">
                {% endif %}
         
          </div>

          <h2 class="entry-title">
            <a href="blog-single.html">{{ publication.titre }}</a>
          </h2>

          <div class="entry-meta">
            <ul>
              <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ publication.user.nom }} {{ publication.user.prenom }}</a></li>
              <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{ publication.date|date("d/m/Y") }}</time></a></li>
              <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-single.html">{{ publication.comments | length }}</a></li>
            </ul>
          </div>

          <div class="entry-content">
            <p>
              {{ publication.text|striptags }}
            </p>

            

          </div>

         

        </article><!-- End blog entry -->

        <div class="blog-comments">

          <h4 class="comments-count">{{ publication.comments | length }} Commentaire(s)</h4>
          {% for comment in publication.comments %}
          <div id="comment-1" class="comment">
            <div class="d-flex">
              <div class="comment-img"><img src="{{ asset('uploads/'~ comment.user.image ) }}" class="rounded-circle float-left" alt=""></div>
              <div>
                <h5><a href="">{{ comment.user.nom }} {{ comment.user.prenom }}</a> </h5>
                <time datetime="2020-01-01">Publié le {{comment.createdAt|date("d/m/Y") }}</time>
                <p>
                  {{comment.content|raw}}
                </p>
                {% if (app.user.id == comment.user.id) or ( is_granted('ROLE_ADMIN') ) %}
                <a href="{{ path('supprimer_commentaire',{'id':comment.id}) }}">                          
                    Supprimer                          
                </a>
                <a href="{{ path('update_comment',{'id':comment.id}) }}">Modifier</a>
                {% endif %}
              </div>
            </div>
          </div><!-- End comment #1 -->
          {% endfor %}

        </div><!-- End blog comments -->

          <div class="reply-form">
            <h4>Laisser un commentaire</h4>


            <div class="col-xs2 col-sm3" id="ajout-commentaire">
              
              {{ form(commentForm) }}
          </div>
          {{ form_start(commentForm,{'attr':{'novalidate':'novalidate'}}) }}       
              <div class="row">
                <div class="col form-group">
                  {{form_widget(commentForm.content,{'attr':{'class':'form-control', 'placeholder':'votre commentaire'}})}}
                  {{form_errors(commentForm.content,{'attr':{'class':'text-danger'}}) }}
                </div>
              </div>
              {{form_widget(commentForm.Ajouter,{'attr':{'class':'getstarted'}})}}
             
              {{ form_end(commentForm) }}       
            

          </div>

        </div><!-- End blog comments -->

      </div><!-- End blog entries list -->

      <div class="col-lg-4">

    

      </div><!-- End blog sidebar -->

    </div>

  </div>

  <!-- Modifier Modal-->
  <div class="modal fade" id="basicModal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modifier Votre Commenaire</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        {{ form_start(form) }}
        <div class="modal-body">
            <div class="form-group ">
                <label class="control-label col-lg-2">Content</label>
                <div class="col-lg-10">
              
                  {{form_widget(form.content,{'attr':{'class':'form-control' }})}}
                 
                </div>
              </div>
        </div>
        
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          {{form_widget(form.Update,{'attr':{'class':'btn btn-theme'}})}}
          
        </div>
        {{ form_end(form) }}
      </div>
    </div>
  </div><!-- End Modifier Modal-->
</section><!-- End Blog Single Section -->


{% endblock %}

templates/publication/edit.html.twig
{% extends 'base2.html.twig' %}
{% block title %}
<title>OutWithUs- Modifier votre publication</title>
{% endblock %}
{% block body %}


<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Modifier votre Publication</h2>
      <ol>
        <li><a href="index.html">Home</a></li>
      </ol>
    </div>

  </div>
</section>
<!-- End Breadcrumbs -->


<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">

    <div class="row">

      <div class="col-lg-8 entries">
  
   
    <div class="row mt">
      <div class="col-lg-12">
        <div class="form-panel">
          <div class="form">
            {{ form_start(f,{'attr':{'class':'cmxform form-horizontal style-form', 'novalidate':'novalidate'}}) }}
              <div class="form-group ">
                <label class="control-label col-lg-2">Titre</label>
                <div class="col-lg-10">
              
                  {{form_widget(f.titre,{'attr':{'class':'form-control', 'placeholder': 'Le titre du publication'}})}}
                  {{form_errors(f.titre,{'attr':{'class':'text-danger'}}) }}
                </div>
              </div>
              <div class="form-group ">
                <label class="control-label col-lg-2">Text</label>
                <div class="col-lg-10">
              
                  {{form_widget(f.text,{'attr':{'class':'form-control'}})}}
                  {{form_errors(f.text,{'attr':{'class':'text-danger'}}) }}
                </div>
              </div>

              <div>
                <label class="control-label col-lg-2">Image du publication</label>
                <div class="col-lg-10">
                  {% if publication.image|length > 0 %}
                <img src="{{ asset('uploads/'~ publication.image ) }}" width="250" height="150" alt="{{ publication.titre }}">
                {% else %}
                <img src="{{ asset('uploads/'~ "Not Found.jpg" ) }}" width="250" height="150" alt="{{ publication.titre }}">
                {% endif %}
                </div>
            </div>

              <div class="form-group ">
                <label class="control-label col-lg-2">Modifier l'image</label>
                <div class="col-lg-10">
              
                  {{form_widget(f.image,{'attr':{'class':'form-control'}})}}
                 
                </div>
              </div>
             
              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                 
                  {{form_widget(f.Modifier,{'attr':{'class':'btn btn-primary'}})}}
                </div>
              </div>
                      {{ form_end(f) }}
          </div>
       
          <br>         
        </div>     
      </div>
      </div>  
      
    </div>     
  </div>
  </div>  

  </section>


 


{% endblock %}